# Generated by Django 4.1.7 on 2023-03-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', models.CharField(max_length=255)),
                ('column2', models.CharField(max_length=255)),
                ('column3', models.CharField(max_length=255)),
            ],
        ),
    ]
