# Generated by Django 4.1.7 on 2023-03-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0003_rename_column_1_mydata_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mydata',
            old_name='first_name',
            new_name='column_1',
        ),
        migrations.AddField(
            model_name='mydata',
            name='column_2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mydata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
