# Generated by Django 4.1.7 on 2023-03-21 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0004_rename_first_name_mydata_column_1_mydata_column_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mydata',
            old_name='column_1',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='mydata',
            old_name='column_2',
            new_name='name',
        ),
    ]
