# Generated by Django 4.1.7 on 2023-03-21 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0005_rename_column_1_mydata_employee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mydata',
            old_name='employee',
            new_name='column_1',
        ),
        migrations.RenameField(
            model_name='mydata',
            old_name='name',
            new_name='column_2',
        ),
    ]
